server:
  port: 8082


hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tap_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: simple

dubbo:
  application:
    name: tap-platform
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    serialization: protobuf
  metrics:
    enable: true
    protocol: prometheus
    port: 9090
  consumer:
    retries: 3
    timeout: 3000
    loadbalance: random
    async: true
  provider:
    executes: 50